name: Continuous integration
on:
  pull_request:
  push:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_gradle:
    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 11
          - os: macos-latest
            java: 11
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run and check formatting
        run: ./gradlew run verGJF
